color: violet
description: null
fieldLayouts:
  f00ef8d9-b10c-4a28-a60e-5277f76636f3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-08T19:44:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0a58e287-e038-4eb7-ab2a-cf4cbdbe013d # Page content
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7e779f3-433c-4f8b-944d-856ad00220da
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea21cde6-ed6d-4134-b16c-97380c9cfb97
        userCondition: null
handle: text
hasTitleField: false
icon: receipt
name: Text
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Post {now}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
