columnSuffix: null
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - f7576aa3-c155-4b54-82c9-8cb8c93495c9 # Callout
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 5358db38-27c0-49b4-b9d3-e68326e79da2 # Image
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 25b2446d-c1d2-4aa1-8184-3147e617f069 # Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - a06e695e-af7f-4a1b-84a7-575ec935e293 # Video
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
