defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5dd08fc8-3ea4-4582-952f-4c0f7ebf409e # Category
handle: workCategories
maxAuthors: 1
name: 'Work Categories'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  58ccb571-6c72-449f-8e7b-6f43c5d416b3: # Sam Headland
    enabledByDefault: true
    hasUrls: true
    template: _pages.twig
    uriFormat: 'work-categories/{slug}'
structure:
  maxLevels: null
  uid: b4b2ba4b-5c4e-4893-b09d-95082b403070
type: structure
